### ISSUE TITLE
After update v1.0.4 inoperable

### ISSUE THREAD

**Issue by Adamv7** [HakCat-Tech/RubberNugget#31]
I did the esptool method to update. Step by step via Linux. Last step to unplug and it should update itself was where it went south. Doesn't turn on anymore.

**Comment by Adamv7** [comment]
Use the chrome method

**Comment by HeinrichII** [comment]
I have the 2.1 nugget board, which it seems has no ZERO button.  I was following the chrome update procedure on an MX Linux lapton.  It erased fine, And I used the esp web flasher, which has a banner that says it's not supported anymore.  I pressed on anyway, and it seemed to program fine...green bar all the way across, then when finished I noticed the bright green LED turned off, and following instructions, I unplugged it (instead of hitting the disconnect button). When I plugged it back in-nothing.  so then I hit the reset button...still nothing.  I reran the procedure using esp web flasher, even though the banner directed to go to esptool. same end result as above.   So then I tried the ESPtool, which is not only a terminal version, but they now have a web flash version also-so used that. Same end result.  Feels like I've bricked this little unit.  P.S. the blue led on the espy board blinks on connection and while hitting the reset button, so it's getting power, also when I plug it into either a windows box or linux, still just a dead little cat. ;(

**Comment by brandonpaiz** [comment]
Hi @HeinrichII,
Here is a picture of where you can find the ZERO button: https://i.imgur.com/rtSSVuv.jpg. Please try again, as the ESP web flasher is known working as of yesterday. If you're still having issues, please let us know! I'd be happy to live-chat with you to get this resolved. Thanks!

**Comment by HeinrichII** [comment]
brandonpaiz, I've got the nugget 2.1 mainboard with the D1 mini riser with the ESP8266MOD flatpack on the D1 board on the riser.  I'm assuming this is a new version, which probably needs updated flash/update procedures.  Looking at the picture you sent, there is no switch at all in that area...I only have a reset button which is on the D1 mini riser board. Livechat would be great to resolve...I'm on signal, threema, and discord.  In hindsight, I probably didn't need to do anything to the nugget,  but probably eventually would need to flash an update.  Thanks for your help.

**Comment by Adamv7** [comment]
Have you guys did the new update? Alex Lynd was up late the night before DF30 finishing it. Kudos to you @AlexLynd and @skickar looking forward to future workshops @NSL or in L.A. area
